# Generated by Django 6.0.1 on 2026-01-30 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(help_text="Feather icon name (e.g., 'shield', 'zap')", max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Dominate the Arena.', max_length=200)),
                ('hero_subtitle', models.CharField(default='Combat Grade Engineering', max_length=100)),
                ('hero_description', models.TextField(default='Precision-engineered combat robots and high-torque propulsion systems for professional robot combat leagues.')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='site/hero/')),
                ('parts_shipped', models.CharField(default='2.4k+', max_length=50)),
                ('tournaments_won', models.CharField(default='150+', max_length=50)),
                ('hologram_image', models.ImageField(blank=True, help_text="Image for the 'Why Choose Us' section", null=True, upload_to='site/visuals/')),
                ('cta_title', models.CharField(default='Ready to Build?', max_length=200)),
                ('cta_description', models.TextField(default='Join the league of professional builders today.')),
                ('cta_btn_text', models.CharField(default='Enter the Arena', max_length=50)),
                ('cta_btn_url', models.CharField(default='/shop/', max_length=200)),
            ],
            options={
                'verbose_name': 'Homepage Settings',
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
    ]
